version: '3.1'
services:
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MyPa$$w0rd
    ports:
      - "27017:27017"
    command: mongod
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=qwerty1234
      - MINIO_DEFAULT_BUCKETS=evup

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
